import type { Product, Category } from '@/types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-audio',
    name: 'Audio & Headphones',
    slug: 'audio',
    description: 'Studio headphones, wireless earpods, and high-fidelity Bluetooth speakers',
    image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
    parent_id: null,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-wearables',
    name: 'Smartwatches',
    slug: 'wearables',
    description: 'OLED smartwatches & fitness trackers with health monitoring',
    image_url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
    parent_id: null,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-km',
    name: 'Keyboards & Mice',
    slug: 'keyboards-mice',
    description: 'Mechanical hot-swappable keyboards and precision ergonomic mice',
    image_url: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&q=80',
    parent_id: null,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: 'cat-desk',
    name: 'Desk Setup',
    slug: 'desk-essentials',
    description: 'Wireless 3-in-1 charging stations, Thunderbolt docks, and desk mats',
    image_url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80',
    parent_id: null,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    title: 'Acoustic Pro ANC Wireless Headphones',
    slug: 'acoustic-pro-anc-headphones',
    description: 'Active Noise Canceling over-ear studio headphones with 40-hour battery life, spatial audio, transparent sound mode, and memory foam ear cushions.',
    price: 14999,
    sale_price: 12999,
    sku: 'AUDIO-ANC-01',
    stock_quantity: 45,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-audio',
    tags: ['audio', 'headphones', 'wireless', 'anc'],
    avg_rating: 4.9,
    review_count: 128,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-1', product_id: 'prod-1', image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80', sort_order: 0, alt_text: 'Acoustic Pro ANC Headphones' },
      { id: 'img-1b', product_id: 'prod-1', image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80', sort_order: 1, alt_text: 'Headphones Side View' },
    ],
    category: { id: 'cat-audio', name: 'Audio & Headphones', slug: 'audio' },
    options: [
      {
        id: 'opt-color-1',
        product_id: 'prod-1',
        name: 'Color',
        sort_order: 0,
        values: [
          { id: 'v-black', option_id: 'opt-color-1', value: 'Matte Black', sort_order: 0 },
          { id: 'v-silver', option_id: 'opt-color-1', value: 'Starlight Silver', sort_order: 1 },
        ],
      },
    ],
    reviews: [
      {
        id: 'rev-1',
        product_id: 'prod-1',
        user_id: 'user-1',
        rating: 5,
        title: 'Best ANC Headphones I have used!',
        body: 'The sound stage is incredibly detailed and noise cancellation works like magic on flights and commuting.',
        is_verified: true,
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
        reviewer: { full_name: 'Aarav Sharma', avatar_url: null },
      },
    ],
  },
  {
    id: 'prod-2',
    title: 'Pulse Earpods Pro Active Noise Canceling',
    slug: 'pulse-earpods-pro',
    description: 'True wireless earpods with transparent mode, IPX7 water resistance, low-latency Bluetooth 5.3, and wireless charging case.',
    price: 8999,
    sale_price: 6999,
    sku: 'AUDIO-EAR-02',
    stock_quantity: 60,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-audio',
    tags: ['audio', 'earpods', 'wireless', 'earbuds'],
    avg_rating: 4.8,
    review_count: 94,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-2', product_id: 'prod-2', image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&q=80', sort_order: 0, alt_text: 'Pulse Earpods Pro' },
    ],
    category: { id: 'cat-audio', name: 'Audio & Headphones', slug: 'audio' },
  },
  {
    id: 'prod-3',
    title: 'Horizon Ultra OLED Smartwatch',
    slug: 'horizon-ultra-oled-smartwatch',
    description: 'Titanium case smartwatch with always-on AMOLED display, heart rate tracking, ECG sensor, dual-frequency GPS, and 7-day battery life.',
    price: 22999,
    sale_price: 19999,
    sku: 'WEAR-WATCH-01',
    stock_quantity: 25,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-wearables',
    tags: ['wearables', 'smartwatch', 'fitness'],
    avg_rating: 4.9,
    review_count: 156,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-3', product_id: 'prod-3', image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80', sort_order: 0, alt_text: 'Horizon OLED Smartwatch' },
      { id: 'img-3b', product_id: 'prod-3', image_url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80', sort_order: 1, alt_text: 'Watch Detail' },
    ],
    category: { id: 'cat-wearables', name: 'Smartwatches', slug: 'wearables' },
  },
  {
    id: 'prod-4',
    title: 'Vanguard Fitness Tracker Band Pro',
    slug: 'vanguard-fitness-band-pro',
    description: 'Ultra-lightweight fitness band with pulse oximeter, sleep stage tracking, water resistance to 50m, and 14-day battery life.',
    price: 4999,
    sale_price: 3999,
    sku: 'WEAR-BAND-02',
    stock_quantity: 80,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-wearables',
    tags: ['wearables', 'fitness', 'smartwatch'],
    avg_rating: 4.6,
    review_count: 42,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-4', product_id: 'prod-4', image_url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&q=80', sort_order: 0, alt_text: 'Vanguard Fitness Band' },
    ],
    category: { id: 'cat-wearables', name: 'Smartwatches', slug: 'wearables' },
  },
  {
    id: 'prod-5',
    title: 'Tactile Pro Wireless Mechanical Keyboard',
    slug: 'tactile-pro-mechanical-keyboard',
    description: 'Hot-swappable mechanical keyboard with custom lubricated linear switches, per-key RGB backlighting, Bluetooth 5.1 & 2.4GHz wireless, and solid aluminum chassis.',
    price: 11999,
    sale_price: 9999,
    sku: 'KM-KEY-01',
    stock_quantity: 30,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-km',
    tags: ['keyboards-mice', 'keyboards', 'mechanical'],
    avg_rating: 5.0,
    review_count: 88,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-5', product_id: 'prod-5', image_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80', sort_order: 0, alt_text: 'Tactile Mechanical Keyboard' },
      { id: 'img-5b', product_id: 'prod-5', image_url: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&q=80', sort_order: 1, alt_text: 'Keyboard Close up' },
    ],
    category: { id: 'cat-km', name: 'Keyboards & Mice', slug: 'keyboards-mice' },
  },
  {
    id: 'prod-6',
    title: 'Apex Precision Ergonomic Wireless Mouse',
    slug: 'apex-precision-ergonomic-mouse',
    description: 'Ergonomic 8K DPI optical sensor mouse with hyper-fast MagSpeed scroll wheel, multi-device Bluetooth pairing, and USB-C fast charging.',
    price: 6999,
    sale_price: 5499,
    sku: 'KM-MOUSE-02',
    stock_quantity: 50,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-km',
    tags: ['keyboards-mice', 'mice', 'ergonomic'],
    avg_rating: 4.8,
    review_count: 67,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-6', product_id: 'prod-6', image_url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&q=80', sort_order: 0, alt_text: 'Apex Precision Ergonomic Mouse' },
    ],
    category: { id: 'cat-km', name: 'Keyboards & Mice', slug: 'keyboards-mice' },
  },
  {
    id: 'prod-7',
    title: 'MagCharge 3-in-1 Fast Wireless Charging Station',
    slug: 'magcharge-3in1-wireless-station',
    description: '15W fast wireless charging stand for Smartphone, Smartwatch, and Earpods simultaneously with weighted aluminum base.',
    price: 4499,
    sale_price: 3499,
    sku: 'DESK-CHARGER-01',
    stock_quantity: 100,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-desk',
    tags: ['desk-essentials', 'charging', 'docks'],
    avg_rating: 4.7,
    review_count: 53,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-7', product_id: 'prod-7', image_url: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=800&q=80', sort_order: 0, alt_text: '3in1 Wireless Charging Station' },
    ],
    category: { id: 'cat-desk', name: 'Desk Setup', slug: 'desk-essentials' },
  },
  {
    id: 'prod-8',
    title: 'Studio Speaker Hi-Fi Bluetooth System',
    slug: 'studio-speaker-hifi-bluetooth',
    description: 'Desktop Bluetooth 5.3 wooden bookshelf speakers with deep bass, optical input, and custom EQ presets.',
    price: 15999,
    sale_price: 13999,
    sku: 'AUDIO-SPK-03',
    stock_quantity: 20,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-audio',
    tags: ['audio', 'speakers', 'hifi'],
    avg_rating: 4.9,
    review_count: 76,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-8', product_id: 'prod-8', image_url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80', sort_order: 0, alt_text: 'Hi-Fi Studio Speakers' },
    ],
    category: { id: 'cat-audio', name: 'Audio & Headphones', slug: 'audio' },
  },
  {
    id: 'prod-9',
    title: 'Titanium Magnetic Strap & Watch Dock',
    slug: 'titanium-magnetic-strap-dock',
    description: 'Grade-2 Titanium metal link watch band with magnetic quick release and fast charging dock.',
    price: 3499,
    sale_price: 2799,
    sku: 'WEAR-ACC-03',
    stock_quantity: 40,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-wearables',
    tags: ['wearables', 'accessories', 'smartwatch'],
    avg_rating: 4.8,
    review_count: 31,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-9', product_id: 'prod-9', image_url: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80', sort_order: 0, alt_text: 'Titanium Link Watch Strap' },
    ],
    category: { id: 'cat-wearables', name: 'Smartwatches', slug: 'wearables' },
  },
  {
    id: 'prod-10',
    title: 'Minimalist Premium Felt Desk Mat XL',
    slug: 'minimalist-felt-desk-mat-xl',
    description: 'Water-resistant merino wool felt desk pad with anti-slip rubberized base and micro-stitched edges.',
    price: 2499,
    sale_price: 1999,
    sku: 'KM-MAT-04',
    stock_quantity: 75,
    track_inventory: true,
    allow_backorders: false,
    status: 'active',
    category_id: 'cat-km',
    tags: ['keyboards-mice', 'mats', 'desk-essentials'],
    avg_rating: 4.9,
    review_count: 112,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    images: [
      { id: 'img-10', product_id: 'prod-10', image_url: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=800&q=80', sort_order: 0, alt_text: 'Minimalist Felt Desk Mat' },
    ],
    category: { id: 'cat-km', name: 'Keyboards & Mice', slug: 'keyboards-mice' },
  },
];

export function getMockProductBySlug(slug: string): Product | null {
  return MOCK_PRODUCTS.find((p) => p.slug === slug) ?? null;
}

export function getMockRelatedProducts(categoryId?: string | null, currentSlug?: string): Product[] {
  return MOCK_PRODUCTS.filter((p) => p.slug !== currentSlug && (categoryId ? p.category_id === categoryId : true)).slice(0, 4);
}
